### ISSUE TITLE
Remove null enties in settings

### ISSUE THREAD

**Issue by alexandredevely** [abcdesktopio/webModules#14]
In Menu
Setting -> System -> User Container, do not print label if data is null.
For example

<img width="1106" alt="wine-auth-user-container" src="https://user-images.githubusercontent.com/12896316/107925867-4ab27c00-6f75-11eb-86b0-32573c2292a9.png">

In this example remove the null label :
Pod namespace
Pod name
Pod ip
Kuebernetes service host

**Comment by kecsou** [comment]
I gonna check this

**Comment by kecsou** [comment]
Done
