### ISSUE TITLE
Sound can't be disable if it has been enabled  

### ISSUE THREAD

**Issue by alexandredevely** [abcdesktopio/webModules#15]
<img width="285" alt="Screenshot 2021-06-22 at 16 38 59" src="https://user-images.githubusercontent.com/12896316/122944745-5cb78780-d378-11eb-9560-3aa61f2181fa.png">

no disable icon, on lower volume level

**Comment by kecsou** [comment]
It is fixed with the new version of oc.user

**Comment by kecsou** [comment]
Fixed
