### ISSUE TITLE
Settings | User containers color header

### ISSUE THREAD

**Issue by alexandredevely** [abcdesktopio/webModules#29]
Please use the tertiary color to main informations value 
example all headers like Hostname, IpAddr, plateform, relaese... should be paint in tertiary color

<img width="1439" alt="Screenshot 2021-02-28 at 14 55 09" src="https://user-images.githubusercontent.com/12896316/109420892-26bf5380-79d5-11eb-9f45-145127d4d2e7.png">

**Comment by kecsou** [comment]
I made a commit on it, please let me know if it is what you are looking for.
