### ISSUE TITLE
Settings:Display color information should use tertiary color  

### ISSUE THREAD

**Issue by alexandredevely** [abcdesktopio/webModules#30]
User tertiary color for header not for data value
example

Web browser use tertiary color, that's correct
But 1440 px should be paint in white and screen in tertiary color 

<img width="1439" alt="Screenshot 2021-02-28 at 14 54 53" src="https://user-images.githubusercontent.com/12896316/109420959-8ae21780-79d5-11eb-9fdc-35530bb1fcac.png">

**Comment by alexandredevely** [comment]
Name
Screen width 
Screen height
Windows innerWidth and innnerHeigth
Ratio
Font size
Orientation

Shoud use tertiary and data value white

**Comment by kecsou** [comment]
Done.
