### ISSUE TITLE
Task manager hide data value

### ISSUE THREAD

**Issue by alexandredevely** [abcdesktopio/webModules#31]
Please make data readable 
the container is and image name need more space

<img width="1439" alt="Screenshot 2021-02-28 at 15 04 43" src="https://user-images.githubusercontent.com/12896316/109421134-62a6e880-79d6-11eb-9d02-810f4a66de54.png">

Hide the binary path is ok but add center for all datas
<img width="936" alt="Screenshot 2021-02-28 at 15 06 55" src="https://user-images.githubusercontent.com/12896316/109421212-ae599200-79d6-11eb-8dbf-f44c28009f5f.png">

**Comment by kecsou** [comment]
Done.
